# Generated by Django 3.2.12 on 2023-06-03 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('role', models.CharField(max_length=10, verbose_name='role')),
            ],
        ),
        migrations.CreateModel(
            name='op_ticket',
            fields=[
                ('op_id', models.AutoField(primary_key=True, serialize=False)),
                ('op_date', models.CharField(max_length=100, verbose_name='date')),
                ('op_status', models.CharField(max_length=100, verbose_name='status')),
                ('op_type', models.CharField(max_length=100, verbose_name='type')),
                ('op_no', models.CharField(max_length=100, verbose_name='op_no')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=200, verbose_name='uname')),
                ('User_address', models.CharField(max_length=200, verbose_name='address')),
                ('User_email', models.CharField(max_length=100, verbose_name='email')),
                ('User_phone', models.CharField(max_length=100, verbose_name='phone')),
                ('User_alt_No', models.CharField(max_length=200, verbose_name='altno')),
                ('User_status', models.CharField(max_length=200, verbose_name='status')),
                ('Log_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('Staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('Staff_name', models.CharField(max_length=100, verbose_name='Name')),
                ('Staff_address', models.CharField(max_length=500, verbose_name='Staff_address')),
                ('Staff_email', models.EmailField(max_length=200, verbose_name='Staff_email')),
                ('Staff_phone', models.CharField(max_length=100, verbose_name='Staff_phone')),
                ('Staff_qualification', models.CharField(max_length=200, verbose_name='Staff_qualification')),
                ('Staff_designation', models.CharField(max_length=100, verbose_name='Staff_designation')),
                ('Staff_experience', models.CharField(max_length=100, verbose_name='Staff_experience')),
                ('Staff_photo', models.FileField(max_length=1000, upload_to='images/', verbose_name='Staff_photo')),
                ('Staff_status', models.CharField(default='', max_length=50, verbose_name='Staff_status')),
                ('Staff_logid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_detail', models.CharField(max_length=100, verbose_name='record')),
                ('record_date', models.CharField(max_length=100, verbose_name='date')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('op', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.op_ticket')),
            ],
        ),
        migrations.AddField(
            model_name='op_ticket',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100, verbose_name='Name')),
                ('doctors', models.ManyToManyField(related_name='departments', to='app.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('Complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('Complaint_subject', models.CharField(max_length=100, verbose_name='subject')),
                ('Complaint_message', models.CharField(max_length=500, verbose_name='message')),
                ('Complaint_date', models.CharField(max_length=100, verbose_name='date')),
                ('Complaint_reply', models.CharField(max_length=500, verbose_name='replay')),
                ('User_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
