# Generated by Django 3.2.12 on 2023-06-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_casesheet_admit'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesheet',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Added', 'Added')], default='Waiting', max_length=20),
        ),
    ]
