# Generated by Django 3.2.12 on 2023-06-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_casesheet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesheet',
            name='status',
            field=models.CharField(default='added', max_length=100),
        ),
    ]
